//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatHCI.Resources.Strings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjekatHCI.Resources.Strings.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addBtn {
            get {
                return ResourceManager.GetString("addBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Data can&apos;t be added!.
        /// </summary>
        public static string addFailedMsg {
            get {
                return ResourceManager.GetString("addFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fault report.
        /// </summary>
        public static string addFaultReportBtn {
            get {
                return ResourceManager.GetString("addFaultReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string addressHdr {
            get {
                return ResourceManager.GetString("addressHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string addressLbl {
            get {
                return ResourceManager.GetString("addressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add service.
        /// </summary>
        public static string addServiceBtn {
            get {
                return ResourceManager.GetString("addServiceBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add spare part.
        /// </summary>
        public static string addSparePartBtn {
            get {
                return ResourceManager.GetString("addSparePartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added!.
        /// </summary>
        public static string addSuccessMsg {
            get {
                return ResourceManager.GetString("addSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amountHdr {
            get {
                return ResourceManager.GetString("amountHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string amountLbl {
            get {
                return ResourceManager.GetString("amountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available:.
        /// </summary>
        public static string availableLbl {
            get {
                return ResourceManager.GetString("availableLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string beginingHdr {
            get {
                return ResourceManager.GetString("beginingHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        public static string beigeTheme {
            get {
                return ResourceManager.GetString("beigeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill preview.
        /// </summary>
        public static string billPreviewBtn {
            get {
                return ResourceManager.GetString("billPreviewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string billsHdr {
            get {
                return ResourceManager.GetString("billsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string blueTheme {
            get {
                return ResourceManager.GetString("blueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId.
        /// </summary>
        public static string clientIdHdr {
            get {
                return ResourceManager.GetString("clientIdHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string clientsHdr {
            get {
                return ResourceManager.GetString("clientsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string codeHdr {
            get {
                return ResourceManager.GetString("codeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string confirmUpdateMsg {
            get {
                return ResourceManager.GetString("confirmUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        public static string costLbl {
            get {
                return ResourceManager.GetString("costLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string dateHdr {
            get {
                return ResourceManager.GetString("dateHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteBtn {
            get {
                return ResourceManager.GetString("deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Data can&apos;t be deleted.
        /// </summary>
        public static string deleteFailedMsg {
            get {
                return ResourceManager.GetString("deleteFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted!.
        /// </summary>
        public static string deleteSuccessMsg {
            get {
                return ResourceManager.GetString("deleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descriptionHdr {
            get {
                return ResourceManager.GetString("descriptionHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string descriptionLbl {
            get {
                return ResourceManager.GetString("descriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string employeesHdr {
            get {
                return ResourceManager.GetString("employeesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled..
        /// </summary>
        public static string emptyFieldsMsg {
            get {
                return ResourceManager.GetString("emptyFieldsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled correctly!.
        /// </summary>
        public static string emptyFieldsWarn {
            get {
                return ResourceManager.GetString("emptyFieldsWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string endingHdr {
            get {
                return ResourceManager.GetString("endingHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string enLbl {
            get {
                return ResourceManager.GetString("enLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault reports.
        /// </summary>
        public static string faultReportsHdr {
            get {
                return ResourceManager.GetString("faultReportsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish repairment.
        /// </summary>
        public static string finishBtn {
            get {
                return ResourceManager.GetString("finishBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string firstnameHdr {
            get {
                return ResourceManager.GetString("firstnameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname:.
        /// </summary>
        public static string firstnameLbl {
            get {
                return ResourceManager.GetString("firstnameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string idHdr {
            get {
                return ResourceManager.GetString("idHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string languageLbl {
            get {
                return ResourceManager.GetString("languageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string lastnameHdr {
            get {
                return ResourceManager.GetString("lastnameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname:.
        /// </summary>
        public static string lastnameLbl {
            get {
                return ResourceManager.GetString("lastnameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string logInBtn {
            get {
                return ResourceManager.GetString("logInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!.
        /// </summary>
        public static string loginFailMsg {
            get {
                return ResourceManager.GetString("loginFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logoutBtn {
            get {
                return ResourceManager.GetString("logoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nameHdr {
            get {
                return ResourceManager.GetString("nameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string nameLbl {
            get {
                return ResourceManager.GetString("nameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string noBtn {
            get {
                return ResourceManager.GetString("noBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of obligations.
        /// </summary>
        public static string numOfObligationsHdr {
            get {
                return ResourceManager.GetString("numOfObligationsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperatorId.
        /// </summary>
        public static string operatorIdHdr {
            get {
                return ResourceManager.GetString("operatorIdHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passwordHdr {
            get {
                return ResourceManager.GetString("passwordHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string passwrdLbl {
            get {
                return ResourceManager.GetString("passwrdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phoneHdr {
            get {
                return ResourceManager.GetString("phoneHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string phoneLbl {
            get {
                return ResourceManager.GetString("phoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string priceHdr {
            get {
                return ResourceManager.GetString("priceHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string purpleTheme {
            get {
                return ResourceManager.GetString("purpleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepairmanId.
        /// </summary>
        public static string repairmanIdHdr {
            get {
                return ResourceManager.GetString("repairmanIdHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairment is finished!.
        /// </summary>
        public static string repairmentFinishedSuccessMsg {
            get {
                return ResourceManager.GetString("repairmentFinishedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Repairment can&apos;t be finished..
        /// </summary>
        public static string repairmentFinishFailMsg {
            get {
                return ResourceManager.GetString("repairmentFinishFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairment id.
        /// </summary>
        public static string repairmentId {
            get {
                return ResourceManager.GetString("repairmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairments.
        /// </summary>
        public static string repairmentsHdr {
            get {
                return ResourceManager.GetString("repairmentsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairment can&apos;t start.
        /// </summary>
        public static string repairmentStartError {
            get {
                return ResourceManager.GetString("repairmentStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairment has started.
        /// </summary>
        public static string repairmentStartSuccess {
            get {
                return ResourceManager.GetString("repairmentStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportId.
        /// </summary>
        public static string reportIdHdr {
            get {
                return ResourceManager.GetString("reportIdHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string servicesHdr {
            get {
                return ResourceManager.GetString("servicesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string showDetailsBtn {
            get {
                return ResourceManager.GetString("showDetailsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare parts.
        /// </summary>
        public static string sparePartsHdr {
            get {
                return ResourceManager.GetString("sparePartsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string srLbl {
            get {
                return ResourceManager.GetString("srLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start repairment.
        /// </summary>
        public static string startRepairmentBtn {
            get {
                return ResourceManager.GetString("startRepairmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string statusHdr {
            get {
                return ResourceManager.GetString("statusHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string statusLbl {
            get {
                return ResourceManager.GetString("statusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string totalHdr {
            get {
                return ResourceManager.GetString("totalHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string totalLbl {
            get {
                return ResourceManager.GetString("totalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string typeHdr {
            get {
                return ResourceManager.GetString("typeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string typeLbl {
            get {
                return ResourceManager.GetString("typeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished repairments.
        /// </summary>
        public static string unfinishedHdr {
            get {
                return ResourceManager.GetString("unfinishedHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string updateBtn {
            get {
                return ResourceManager.GetString("updateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Data can&apos;t be updated!.
        /// </summary>
        public static string updateFailedMsg {
            get {
                return ResourceManager.GetString("updateFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        public static string updateSuccessMsg {
            get {
                return ResourceManager.GetString("updateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string usernameHdr {
            get {
                return ResourceManager.GetString("usernameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string usernameLbl {
            get {
                return ResourceManager.GetString("usernameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesBtn {
            get {
                return ResourceManager.GetString("yesBtn", resourceCulture);
            }
        }
    }
}
